---
- ec2_vpc_net:
    name: "{{ openshift_provisioning_aws_vpc_name }}"
    cidr_block: "{{ openshift_provisioning_aws_vpc_cidr }}"
    dns_hostnames: yes
    dns_support: yes
    region: "{{ openshift_provisioning_aws_region }}"
    tags:
      openshift_cluster_id: "{{ openshift_cluster_id }}"
      openshift_env_id: "{{ openshift_env_id }}"
    tenancy: "{{ openshift_provisioning_aws_vpc_tenancy }}"
  register: create_vpc_result

- debug: var=openshift_provisioning_aws_vpc_tenancy
- debug: var=create_vpc_result
